project_id = "toeqcwzbxvhoxewifusk"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[postgres]
port = 54322
db_port = 5432
shadow_port = 54320
major_version = 15

[api]
enabled = true
port = 54321
schemes = ["http", "https"]
schemas = ["public", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
studio_port = 54323

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"