-- Add political fields to governors
ALTER TABLE governors 
ADD COLUMN IF NOT EXISTS party TEXT,
ADD COLUMN IF NOT EXISTS coalition TEXT,
ADD COLUMN IF NOT EXISTS term_start DATE,
ADD COLUMN IF NOT EXISTS term_end DATE,
ADD COLUMN IF NOT EXISTS biography TEXT,
ADD COLUMN IF NOT EXISTS office_location TEXT,
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT;

-- Add political fields to members_of_parliament
ALTER TABLE members_of_parliament 
ADD COLUMN IF NOT EXISTS party TEXT,
ADD COLUMN IF NOT EXISTS coalition TEXT,
ADD COLUMN IF NOT EXISTS term_start DATE,
ADD COLUMN IF NOT EXISTS term_end DATE,
ADD COLUMN IF NOT EXISTS biography TEXT,
ADD COLUMN IF NOT EXISTS office_location TEXT,
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT;

-- Add political fields to senators
ALTER TABLE senators 
ADD COLUMN IF NOT EXISTS party TEXT,
ADD COLUMN IF NOT EXISTS coalition TEXT,
ADD COLUMN IF NOT EXISTS term_start DATE,
ADD COLUMN IF NOT EXISTS term_end DATE,
ADD COLUMN IF NOT EXISTS biography TEXT,
ADD COLUMN IF NOT EXISTS office_location TEXT,
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT;
