CREATE TABLE IF NOT EXISTS governors (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    county TEXT NOT NULL,
    party TEXT NOT NULL,
    photo_url TEXT,
    email TEXT,
    phone TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert all 47 governors
INSERT INTO governors (name, county, party, email) VALUES
    ('Amos Nyaribo', 'Nyamira', 'UPA', 'governor@nyamira.go.ke'),
    ('Abdi Hassan Guyo', 'Isiolo', 'JP', 'governor@isiolo.go.ke'),
    ('Abdulswamad Nassir', 'Mombasa', 'ODM', 'governor@mombasa.go.ke'),
    ('Ahmed Abdullahi', 'Wajir', 'ODM', 'governor@wajir.go.ke'),
    ('Anyang Nyongo', 'Kisumu', 'ODM', 'governor@kisumu.go.ke'),
    ('Wilber Ottichilo', 'Vihiga', 'ODM', 'governor@vihiga.go.ke'),
    ('Cecily Mbarire', 'Embu', 'UDA', 'governor@embu.go.ke'),
    ('Dhadho Godhana', 'Tana River', 'ODM', 'governor@tanariver.go.ke'),
    ('Fatuma Achani', 'Kwale', 'UDA', 'governor@kwale.go.ke'),
    ('Fernandes Barasa', 'Kakamega', 'ODM', 'governor@kakamega.go.ke'),
    ('Gideon Mungaro', 'Kilifi', 'ODM', 'governor@kilifi.go.ke'),    
    ('Gladys Wanga', 'Homa Bay', 'ODM', 'governor@homabay.go.ke'),
    ('Hillary Barchok', 'Bomet', 'UDA', 'governor@bomet.go.ke'),
    ('James Orengo', 'Siaya', 'ODM', 'governor@siaya.go.ke'),
    ('Jeremiah Lomorukai', 'Turkana', 'ODM', 'governor@turkana.go.ke'),
    ('Johnson Sakaja', 'Nairobi', 'UDA', 'governor@nairobi.go.ke'),
    ('Jonathan Chepkwony', 'Uasin Gishu', 'UDA', 'governor@uasingishu.go.ke'),
    ('Joseph Ole Lenku', 'Kajiado', 'ODM', 'governor@kajiado.go.ke'),
    ('Joshua Irungu', 'Laikipia', 'UDA', 'governor@laikipia.go.ke'),
    ('Kawira Mwangaza', 'Meru', 'Independent', 'governor@meru.go.ke'),
    ('Kenneth Lusaka', 'Bungoma', 'FORD-K', 'governor@bungoma.go.ke'),
    ('Kimani Wamatangi', 'Kiambu', 'UDA', 'governor@kiambu.go.ke'),
    ('Kiprono Sang', 'Kericho', 'UDA', 'governor@kericho.go.ke'),
    ('Mohamed Khalif', 'Mandera', 'UDM', 'governor@mandera.go.ke'),
    ('Mutahi Kahiga', 'Nyeri', 'UDA', 'governor@nyeri.go.ke'),
    ('Mutula Kilonzo Jr', 'Makueni', 'WDM', 'governor@makueni.go.ke'),
    ('Muthomi Njuki', 'Tharaka Nithi', 'UDA', 'governor@tharakanithi.go.ke'),
    ('Nathif Jama', 'Garissa', 'ODM', 'governor@garissa.go.ke'),
    ('Patrick Ntutu', 'Narok', 'UDA', 'governor@narok.go.ke'),
    ('Paul Otuoma', 'Busia', 'ODM', 'governor@busia.go.ke'),
    ('Simon Kachapin', 'West Pokot', 'UDA', 'governor@westpokot.go.ke'),
    ('Stephen Sang', 'Nandi', 'UDA', 'governor@nandi.go.ke'),
    ('Susan Kihika', 'Nakuru', 'UDA', 'governor@nakuru.go.ke'),
    ('Wavinya Ndeti', 'Machakos', 'WDM', 'governor@machakos.go.ke'),
    ('Wisley Rotich', 'Elgeyo Marakwet', 'UDA', 'governor@elgeyomarakwet.go.ke')
ON CONFLICT (name) DO UPDATE 
SET county = EXCLUDED.county,
    party = EXCLUDED.party,
    email = EXCLUDED.email;
